name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/lovelace-minimal-sun-moon-card/lovelace-minimal-sun-moon-card
          npm install
          npm run build

      # Upload build file to the release as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/lovelace-minimal-sun-moon-card/lovelace-minimal-sun-moon-card/dist/sun-moon-card.js
          asset_name: hourly-weather.js
          tag: ${{ github.ref }}
          overwrite: true
